### ISSUE TITLE
Security: keys exposed

### ISSUE THREAD

**Issue by dnbert** [am-tech/boop-source#1]
Hello,

During an audit of public facing repositories we have identified that your repository exposes api and secret keys that could be used nefariously:

https://github.com/am-tech/boop-source/blob/c8c0dd33521c2477b1b59a4035e652f3b3069460/screens/LoginScreen.js#L47

We've ensured that this key had already been disabled, but wanted to inform you as well. We suggest using a templating system, variable injection or even a pre-commit check in the future to make sure that keys aren't uploaded.

**Comment by ps-mariotacke** [comment]
Thanks Brett, this project was built during a hackathon with (sandbox?) credentials and is no longer in use. Appreciate the notification though!

**Comment by mariotacke** [comment]
Thanks Brett, this project was built during a hackathon with (sandbox?) credentials and is no longer in use. Appreciate the notification though!
